name: GitHub Stats and Streak

on:
  schedule:
    - cron: "0 0 * * *" # Updates every night at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Streak and Stats
        uses: stats-organization/github-readme-stats-action@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          user: sainithinpamulaparthi
          output_dir: stats-output
